/* This file is generated by python scripts. Don't edit this file directly.
 */

#ifndef CHEWING_TABLE_H
#define CHEWING_TABLE_H

namespace pinyin{

const chewing_symbol_item_t chewing_standard_initials[] = {
{'1'  , "ㄅ"},
{'2'  , "ㄉ"},
{'5'  , "ㄓ"},
{'a'  , "ㄇ"},
{'b'  , "ㄖ"},
{'c'  , "ㄏ"},
{'d'  , "ㄎ"},
{'e'  , "ㄍ"},
{'f'  , "ㄑ"},
{'g'  , "ㄕ"},
{'h'  , "ㄘ"},
{'n'  , "ㄙ"},
{'q'  , "ㄆ"},
{'r'  , "ㄐ"},
{'s'  , "ㄋ"},
{'t'  , "ㄔ"},
{'v'  , "ㄒ"},
{'w'  , "ㄊ"},
{'x'  , "ㄌ"},
{'y'  , "ㄗ"},
{'z'  , "ㄈ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_standard_middles[] = {
{'j'  , "ㄨ"},
{'m'  , "ㄩ"},
{'u'  , "ㄧ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_standard_finals[] = {
{','  , "ㄝ"},
{'-'  , "ㄦ"},
{'.'  , "ㄡ"},
{'/'  , "ㄥ"},
{'0'  , "ㄢ"},
{'8'  , "ㄚ"},
{'9'  , "ㄞ"},
{';'  , "ㄤ"},
{'i'  , "ㄛ"},
{'k'  , "ㄜ"},
{'l'  , "ㄠ"},
{'o'  , "ㄟ"},
{'p'  , "ㄣ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_standard_tones[] = {
{' '  , 1},
{'3'  , 3},
{'4'  , 4},
{'6'  , 2},
{'7'  , 5},
{'\0', 0}
};

const chewing_symbol_item_t chewing_ginyieh_initials[] = {
{'2'  , "ㄅ"},
{'3'  , "ㄉ"},
{'6'  , "ㄓ"},
{'b'  , "ㄒ"},
{'c'  , "ㄌ"},
{'d'  , "ㄋ"},
{'e'  , "ㄊ"},
{'f'  , "ㄎ"},
{'g'  , "ㄑ"},
{'h'  , "ㄕ"},
{'j'  , "ㄘ"},
{'m'  , "ㄙ"},
{'n'  , "ㄖ"},
{'r'  , "ㄍ"},
{'s'  , "ㄇ"},
{'t'  , "ㄐ"},
{'u'  , "ㄗ"},
{'v'  , "ㄏ"},
{'w'  , "ㄆ"},
{'x'  , "ㄈ"},
{'y'  , "ㄔ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_ginyieh_middles[] = {
{'8'  , "ㄧ"},
{'i'  , "ㄨ"},
{'k'  , "ㄩ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_ginyieh_finals[] = {
{'\'' , "ㄥ"},
{','  , "ㄚ"},
{'-'  , "ㄣ"},
{'.'  , "ㄞ"},
{'/'  , "ㄢ"},
{'0'  , "ㄟ"},
{'9'  , "ㄛ"},
{';'  , "ㄡ"},
{'='  , "ㄦ"},
{'['  , "ㄤ"},
{'l'  , "ㄝ"},
{'o'  , "ㄜ"},
{'p'  , "ㄠ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_ginyieh_tones[] = {
{' '  , 1},
{'1'  , 5},
{'a'  , 3},
{'q'  , 2},
{'z'  , 4},
{'\0', 0}
};

const chewing_symbol_item_t chewing_eten_initials[] = {
{'\'' , "ㄘ"},
{','  , "ㄓ"},
{'.'  , "ㄔ"},
{'/'  , "ㄕ"},
{'7'  , "ㄑ"},
{';'  , "ㄗ"},
{'b'  , "ㄅ"},
{'c'  , "ㄒ"},
{'d'  , "ㄉ"},
{'f'  , "ㄈ"},
{'g'  , "ㄐ"},
{'h'  , "ㄏ"},
{'j'  , "ㄖ"},
{'k'  , "ㄎ"},
{'l'  , "ㄌ"},
{'m'  , "ㄇ"},
{'n'  , "ㄋ"},
{'p'  , "ㄆ"},
{'s'  , "ㄙ"},
{'t'  , "ㄊ"},
{'v'  , "ㄍ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_eten_middles[] = {
{'e'  , "ㄧ"},
{'u'  , "ㄩ"},
{'x'  , "ㄨ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_eten_finals[] = {
{'-'  , "ㄥ"},
{'0'  , "ㄤ"},
{'8'  , "ㄢ"},
{'9'  , "ㄣ"},
{'='  , "ㄦ"},
{'a'  , "ㄚ"},
{'i'  , "ㄞ"},
{'o'  , "ㄛ"},
{'q'  , "ㄟ"},
{'r'  , "ㄜ"},
{'w'  , "ㄝ"},
{'y'  , "ㄡ"},
{'z'  , "ㄠ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_eten_tones[] = {
{' '  , 1},
{'1'  , 5},
{'2'  , 2},
{'3'  , 3},
{'4'  , 4},
{'\0', 0}
};

const chewing_symbol_item_t chewing_ibm_initials[] = {
{'-'  , "ㄏ"},
{'0'  , "ㄎ"},
{'1'  , "ㄅ"},
{'2'  , "ㄆ"},
{'3'  , "ㄇ"},
{'4'  , "ㄈ"},
{'5'  , "ㄉ"},
{'6'  , "ㄊ"},
{'7'  , "ㄋ"},
{'8'  , "ㄌ"},
{'9'  , "ㄍ"},
{'e'  , "ㄒ"},
{'i'  , "ㄗ"},
{'o'  , "ㄘ"},
{'p'  , "ㄙ"},
{'q'  , "ㄐ"},
{'r'  , "ㄓ"},
{'t'  , "ㄔ"},
{'u'  , "ㄖ"},
{'w'  , "ㄑ"},
{'y'  , "ㄕ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_ibm_middles[] = {
{'a'  , "ㄧ"},
{'d'  , "ㄩ"},
{'s'  , "ㄨ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_ibm_finals[] = {
{';'  , "ㄠ"},
{'b'  , "ㄥ"},
{'c'  , "ㄣ"},
{'f'  , "ㄚ"},
{'g'  , "ㄛ"},
{'h'  , "ㄜ"},
{'j'  , "ㄝ"},
{'k'  , "ㄞ"},
{'l'  , "ㄟ"},
{'n'  , "ㄦ"},
{'v'  , "ㄤ"},
{'x'  , "ㄢ"},
{'z'  , "ㄡ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_ibm_tones[] = {
{' '  , 1},
{','  , 3},
{'.'  , 4},
{'/'  , 5},
{'m'  , 2},
{'\0', 0}
};

const chewing_symbol_item_t chewing_hsu_initials[] = {
{'a'  , "ㄘ"},
{'b'  , "ㄅ"},
{'c'  , "ㄒ"},
{'c'  , "ㄕ"},
{'d'  , "ㄉ"},
{'f'  , "ㄈ"},
{'g'  , "ㄍ"},
{'h'  , "ㄏ"},
{'j'  , "ㄐ"},
{'j'  , "ㄓ"},
{'k'  , "ㄎ"},
{'l'  , "ㄌ"},
{'m'  , "ㄇ"},
{'n'  , "ㄋ"},
{'p'  , "ㄆ"},
{'r'  , "ㄖ"},
{'s'  , "ㄙ"},
{'t'  , "ㄊ"},
{'v'  , "ㄑ"},
{'v'  , "ㄔ"},
{'z'  , "ㄗ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_hsu_middles[] = {
{'e'  , "ㄧ"},
{'u'  , "ㄩ"},
{'x'  , "ㄨ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_hsu_finals[] = {
{'a'  , "ㄟ"},
{'e'  , "ㄝ"},
{'g'  , "ㄜ"},
{'h'  , "ㄛ"},
{'i'  , "ㄞ"},
{'k'  , "ㄤ"},
{'l'  , "ㄥ"},
{'l'  , "ㄦ"},
{'m'  , "ㄢ"},
{'n'  , "ㄣ"},
{'o'  , "ㄡ"},
{'w'  , "ㄠ"},
{'y'  , "ㄚ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_hsu_tones[] = {
{' '  , 1},
{'d'  , 2},
{'f'  , 3},
{'j'  , 4},
{'s'  , 5},
{'\0', 0}
};

const chewing_symbol_item_t chewing_eten26_initials[] = {
{'b'  , "ㄅ"},
{'c'  , "ㄒ"},
{'c'  , "ㄕ"},
{'d'  , "ㄉ"},
{'f'  , "ㄈ"},
{'g'  , "ㄐ"},
{'g'  , "ㄓ"},
{'h'  , "ㄏ"},
{'j'  , "ㄖ"},
{'k'  , "ㄎ"},
{'l'  , "ㄌ"},
{'m'  , "ㄇ"},
{'n'  , "ㄋ"},
{'p'  , "ㄆ"},
{'q'  , "ㄗ"},
{'s'  , "ㄙ"},
{'t'  , "ㄊ"},
{'v'  , "ㄍ"},
{'v'  , "ㄑ"},
{'w'  , "ㄘ"},
{'y'  , "ㄔ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_eten26_middles[] = {
{'e'  , "ㄧ"},
{'u'  , "ㄩ"},
{'x'  , "ㄨ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_eten26_finals[] = {
{'a'  , "ㄚ"},
{'h'  , "ㄦ"},
{'i'  , "ㄞ"},
{'l'  , "ㄥ"},
{'m'  , "ㄢ"},
{'n'  , "ㄣ"},
{'o'  , "ㄛ"},
{'p'  , "ㄡ"},
{'q'  , "ㄟ"},
{'r'  , "ㄜ"},
{'t'  , "ㄤ"},
{'w'  , "ㄝ"},
{'z'  , "ㄠ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_eten26_tones[] = {
{' '  , 1},
{'d'  , 5},
{'f'  , 2},
{'j'  , 3},
{'k'  , 4},
{'\0', 0}
};

const chewing_symbol_item_t chewing_standard_dvorak_initials[] = {
{'\'' , "ㄆ"},
{','  , "ㄊ"},
{'.'  , "ㄍ"},
{'1'  , "ㄅ"},
{'2'  , "ㄉ"},
{'5'  , "ㄓ"},
{';'  , "ㄈ"},
{'a'  , "ㄇ"},
{'b'  , "ㄙ"},
{'d'  , "ㄘ"},
{'e'  , "ㄎ"},
{'f'  , "ㄗ"},
{'i'  , "ㄕ"},
{'j'  , "ㄏ"},
{'k'  , "ㄒ"},
{'o'  , "ㄋ"},
{'p'  , "ㄐ"},
{'q'  , "ㄌ"},
{'u'  , "ㄑ"},
{'x'  , "ㄖ"},
{'y'  , "ㄔ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_standard_dvorak_middles[] = {
{'g'  , "ㄧ"},
{'h'  , "ㄨ"},
{'m'  , "ㄩ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_standard_dvorak_finals[] = {
{'0'  , "ㄢ"},
{'8'  , "ㄚ"},
{'9'  , "ㄞ"},
{'['  , "ㄦ"},
{'c'  , "ㄛ"},
{'l'  , "ㄣ"},
{'n'  , "ㄠ"},
{'r'  , "ㄟ"},
{'s'  , "ㄤ"},
{'t'  , "ㄜ"},
{'v'  , "ㄡ"},
{'w'  , "ㄝ"},
{'z'  , "ㄥ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_standard_dvorak_tones[] = {
{' '  , 1},
{'3'  , 3},
{'4'  , 4},
{'6'  , 2},
{'7'  , 5},
{'\0', 0}
};

const chewing_symbol_item_t chewing_hsu_dvorak_initials[] = {
{'a'  , "ㄘ"},
{'b'  , "ㄅ"},
{'c'  , "ㄒ"},
{'c'  , "ㄕ"},
{'d'  , "ㄉ"},
{'f'  , "ㄈ"},
{'g'  , "ㄍ"},
{'h'  , "ㄏ"},
{'j'  , "ㄐ"},
{'j'  , "ㄓ"},
{'k'  , "ㄎ"},
{'l'  , "ㄌ"},
{'m'  , "ㄇ"},
{'n'  , "ㄋ"},
{'p'  , "ㄆ"},
{'r'  , "ㄖ"},
{'s'  , "ㄙ"},
{'t'  , "ㄊ"},
{'v'  , "ㄑ"},
{'v'  , "ㄔ"},
{'z'  , "ㄗ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_hsu_dvorak_middles[] = {
{'e'  , "ㄧ"},
{'u'  , "ㄩ"},
{'x'  , "ㄨ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_hsu_dvorak_finals[] = {
{'a'  , "ㄟ"},
{'e'  , "ㄝ"},
{'g'  , "ㄜ"},
{'h'  , "ㄛ"},
{'i'  , "ㄞ"},
{'k'  , "ㄤ"},
{'l'  , "ㄥ"},
{'l'  , "ㄦ"},
{'m'  , "ㄢ"},
{'n'  , "ㄣ"},
{'o'  , "ㄡ"},
{'w'  , "ㄠ"},
{'y'  , "ㄚ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_hsu_dvorak_tones[] = {
{' '  , 1},
{'d'  , 2},
{'f'  , 3},
{'j'  , 4},
{'s'  , 5},
{'\0', 0}
};

const chewing_symbol_item_t chewing_dachen_cp26_initials[] = {
{'a'  , "ㄇ"},
{'b'  , "ㄖ"},
{'c'  , "ㄏ"},
{'d'  , "ㄎ"},
{'e'  , "ㄍ"},
{'f'  , "ㄑ"},
{'g'  , "ㄕ"},
{'h'  , "ㄘ"},
{'n'  , "ㄙ"},
{'q'  , "ㄅ"},
{'q'  , "ㄆ"},
{'r'  , "ㄐ"},
{'s'  , "ㄋ"},
{'t'  , "ㄓ"},
{'t'  , "ㄔ"},
{'v'  , "ㄒ"},
{'w'  , "ㄉ"},
{'w'  , "ㄊ"},
{'x'  , "ㄌ"},
{'y'  , "ㄗ"},
{'z'  , "ㄈ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_dachen_cp26_middles[] = {
{'j'  , "ㄨ"},
{'m'  , "ㄩ"},
{'u'  , "ㄧ"},
{'\0', NULL}
};

const chewing_symbol_item_t chewing_dachen_cp26_finals[] = {
{'b'  , "ㄝ"},
{'i'  , "ㄛ"},
{'i'  , "ㄞ"},
{'k'  , "ㄜ"},
{'l'  , "ㄠ"},
{'l'  , "ㄤ"},
{'m'  , "ㄡ"},
{'n'  , "ㄥ"},
{'o'  , "ㄟ"},
{'o'  , "ㄢ"},
{'p'  , "ㄣ"},
{'p'  , "ㄦ"},
{'u'  , "ㄚ"},
{'\0', NULL}
};

const chewing_tone_item_t chewing_dachen_cp26_tones[] = {
{' '  , 1},
{'d'  , 4},
{'e'  , 2},
{'r'  , 3},
{'y'  , 5},
{'\0', 0}
};

const char * chewing_tone_table[CHEWING_NUMBER_OF_TONES] = {
"",
"ˉ",
"ˊ",
"ˇ",
"ˋ",
"˙"
};

};

#endif
